server:
  port: 8888
spring:
  application:
    name: PPM-Backend
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ppm
    username: root
    password: root
  config:
    import:
      - classpath:/messages.yml

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

token:
  access-expiration-time: 43200000          # 12H
  refresh-expiration-time: 604800000        # 7D
  secret: temp


#logging:
#  level:
#    root: debug