apiVersion: v1
kind: Service
metadata:
  name: ppm-front
  namespace: default
spec:
  selector:
    app: ppm-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
