apiVersion: v1
kind: Service
metadata:
  name: ppm-back
  namespace: default
spec:
  selector:
    app: ppm-back
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
